//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndWindowsForms.BackendWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ClienteModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        private int IngresosField;
        
        private int EgresosField;
        
        private int PasivosField;
        
        private int ScoringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdClienteField, value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Ingresos {
            get {
                return this.IngresosField;
            }
            set {
                if ((this.IngresosField.Equals(value) != true)) {
                    this.IngresosField = value;
                    this.RaisePropertyChanged("Ingresos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Egresos {
            get {
                return this.EgresosField;
            }
            set {
                if ((this.EgresosField.Equals(value) != true)) {
                    this.EgresosField = value;
                    this.RaisePropertyChanged("Egresos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Pasivos {
            get {
                return this.PasivosField;
            }
            set {
                if ((this.PasivosField.Equals(value) != true)) {
                    this.PasivosField = value;
                    this.RaisePropertyChanged("Pasivos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Scoring {
            get {
                return this.ScoringField;
            }
            set {
                if ((this.ScoringField.Equals(value) != true)) {
                    this.ScoringField = value;
                    this.RaisePropertyChanged("Scoring");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditosModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CreditosModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdCreditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private int MontoField;
        
        private int PlazoField;
        
        private float TeaField;
        
        private float TnmField;
        
        private int TotalInteresField;
        
        private int TotalMontoInteresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdCredito {
            get {
                return this.IdCreditoField;
            }
            set {
                if ((this.IdCreditoField.Equals(value) != true)) {
                    this.IdCreditoField = value;
                    this.RaisePropertyChanged("IdCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Plazo {
            get {
                return this.PlazoField;
            }
            set {
                if ((this.PlazoField.Equals(value) != true)) {
                    this.PlazoField = value;
                    this.RaisePropertyChanged("Plazo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public float Tea {
            get {
                return this.TeaField;
            }
            set {
                if ((this.TeaField.Equals(value) != true)) {
                    this.TeaField = value;
                    this.RaisePropertyChanged("Tea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public float Tnm {
            get {
                return this.TnmField;
            }
            set {
                if ((this.TnmField.Equals(value) != true)) {
                    this.TnmField = value;
                    this.RaisePropertyChanged("Tnm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int TotalInteres {
            get {
                return this.TotalInteresField;
            }
            set {
                if ((this.TotalInteresField.Equals(value) != true)) {
                    this.TotalInteresField = value;
                    this.RaisePropertyChanged("TotalInteres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int TotalMontoInteres {
            get {
                return this.TotalMontoInteresField;
            }
            set {
                if ((this.TotalMontoInteresField.Equals(value) != true)) {
                    this.TotalMontoInteresField = value;
                    this.RaisePropertyChanged("TotalMontoInteres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BackendWebService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListarClientesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarClientes", ReplyAction="*")]
        FrontEndWindowsForms.BackendWebService.ListarClientesResponse ListarClientes(FrontEndWindowsForms.BackendWebService.ListarClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.ListarClientesResponse> ListarClientesAsync(FrontEndWindowsForms.BackendWebService.ListarClientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cedula del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarCliente", ReplyAction="*")]
        FrontEndWindowsForms.BackendWebService.ConsultarClienteResponse ConsultarCliente(FrontEndWindowsForms.BackendWebService.ConsultarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.ConsultarClienteResponse> ConsultarClienteAsync(FrontEndWindowsForms.BackendWebService.ConsultarClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cedula del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarCliente", ReplyAction="*")]
        FrontEndWindowsForms.BackendWebService.EliminarClienteResponse EliminarCliente(FrontEndWindowsForms.BackendWebService.EliminarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.EliminarClienteResponse> EliminarClienteAsync(FrontEndWindowsForms.BackendWebService.EliminarClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cedula del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCliente", ReplyAction="*")]
        FrontEndWindowsForms.BackendWebService.InsertarClienteResponse InsertarCliente(FrontEndWindowsForms.BackendWebService.InsertarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.InsertarClienteResponse> InsertarClienteAsync(FrontEndWindowsForms.BackendWebService.InsertarClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cedula del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarCliente", ReplyAction="*")]
        FrontEndWindowsForms.BackendWebService.ModificarClienteResponse ModificarCliente(FrontEndWindowsForms.BackendWebService.ModificarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.ModificarClienteResponse> ModificarClienteAsync(FrontEndWindowsForms.BackendWebService.ModificarClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cedula del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarViabilidadCredito", ReplyAction="*")]
        FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoResponse ValidarViabilidadCredito(FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarViabilidadCredito", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoResponse> ValidarViabilidadCreditoAsync(FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento producto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCredito", ReplyAction="*")]
        FrontEndWindowsForms.BackendWebService.InsertarCreditoResponse InsertarCredito(FrontEndWindowsForms.BackendWebService.InsertarCreditoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCredito", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.InsertarCreditoResponse> InsertarCreditoAsync(FrontEndWindowsForms.BackendWebService.InsertarCreditoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cedula del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarProductosPorCliente", ReplyAction="*")]
        FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteResponse ConsultarProductosPorCliente(FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarProductosPorCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteResponse> ConsultarProductosPorClienteAsync(FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarClientes", Namespace="http://tempuri.org/", Order=0)]
        public FrontEndWindowsForms.BackendWebService.ListarClientesRequestBody Body;
        
        public ListarClientesRequest() {
        }
        
        public ListarClientesRequest(FrontEndWindowsForms.BackendWebService.ListarClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarClientesRequestBody {
        
        public ListarClientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarClientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEndWindowsForms.BackendWebService.ListarClientesResponseBody Body;
        
        public ListarClientesResponse() {
        }
        
        public ListarClientesResponse(FrontEndWindowsForms.BackendWebService.ListarClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEndWindowsForms.BackendWebService.ClienteModel[] ListarClientesResult;
        
        public ListarClientesResponseBody() {
        }
        
        public ListarClientesResponseBody(FrontEndWindowsForms.BackendWebService.ClienteModel[] ListarClientesResult) {
            this.ListarClientesResult = ListarClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarCliente", Namespace="http://tempuri.org/", Order=0)]
        public FrontEndWindowsForms.BackendWebService.ConsultarClienteRequestBody Body;
        
        public ConsultarClienteRequest() {
        }
        
        public ConsultarClienteRequest(FrontEndWindowsForms.BackendWebService.ConsultarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula;
        
        public ConsultarClienteRequestBody() {
        }
        
        public ConsultarClienteRequestBody(string cedula) {
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEndWindowsForms.BackendWebService.ConsultarClienteResponseBody Body;
        
        public ConsultarClienteResponse() {
        }
        
        public ConsultarClienteResponse(FrontEndWindowsForms.BackendWebService.ConsultarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarClienteResult;
        
        public ConsultarClienteResponseBody() {
        }
        
        public ConsultarClienteResponseBody(string ConsultarClienteResult) {
            this.ConsultarClienteResult = ConsultarClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarCliente", Namespace="http://tempuri.org/", Order=0)]
        public FrontEndWindowsForms.BackendWebService.EliminarClienteRequestBody Body;
        
        public EliminarClienteRequest() {
        }
        
        public EliminarClienteRequest(FrontEndWindowsForms.BackendWebService.EliminarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula;
        
        public EliminarClienteRequestBody() {
        }
        
        public EliminarClienteRequestBody(string cedula) {
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEndWindowsForms.BackendWebService.EliminarClienteResponseBody Body;
        
        public EliminarClienteResponse() {
        }
        
        public EliminarClienteResponse(FrontEndWindowsForms.BackendWebService.EliminarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminarClienteResult;
        
        public EliminarClienteResponseBody() {
        }
        
        public EliminarClienteResponseBody(string EliminarClienteResult) {
            this.EliminarClienteResult = EliminarClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarCliente", Namespace="http://tempuri.org/", Order=0)]
        public FrontEndWindowsForms.BackendWebService.InsertarClienteRequestBody Body;
        
        public InsertarClienteRequest() {
        }
        
        public InsertarClienteRequest(FrontEndWindowsForms.BackendWebService.InsertarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ingresos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int egresos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int pasivos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int scoring;
        
        public InsertarClienteRequestBody() {
        }
        
        public InsertarClienteRequestBody(string cedula, string nombre, string direccion, int ingresos, int egresos, int pasivos, int scoring) {
            this.cedula = cedula;
            this.nombre = nombre;
            this.direccion = direccion;
            this.ingresos = ingresos;
            this.egresos = egresos;
            this.pasivos = pasivos;
            this.scoring = scoring;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEndWindowsForms.BackendWebService.InsertarClienteResponseBody Body;
        
        public InsertarClienteResponse() {
        }
        
        public InsertarClienteResponse(FrontEndWindowsForms.BackendWebService.InsertarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarClienteResult;
        
        public InsertarClienteResponseBody() {
        }
        
        public InsertarClienteResponseBody(string InsertarClienteResult) {
            this.InsertarClienteResult = InsertarClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarCliente", Namespace="http://tempuri.org/", Order=0)]
        public FrontEndWindowsForms.BackendWebService.ModificarClienteRequestBody Body;
        
        public ModificarClienteRequest() {
        }
        
        public ModificarClienteRequest(FrontEndWindowsForms.BackendWebService.ModificarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int ingresos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string egresos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pasivos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int scoring;
        
        public ModificarClienteRequestBody() {
        }
        
        public ModificarClienteRequestBody(int idCliente, string cedula, string nombre, string direccion, int ingresos, string egresos, int pasivos, int scoring) {
            this.idCliente = idCliente;
            this.cedula = cedula;
            this.nombre = nombre;
            this.direccion = direccion;
            this.ingresos = ingresos;
            this.egresos = egresos;
            this.pasivos = pasivos;
            this.scoring = scoring;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEndWindowsForms.BackendWebService.ModificarClienteResponseBody Body;
        
        public ModificarClienteResponse() {
        }
        
        public ModificarClienteResponse(FrontEndWindowsForms.BackendWebService.ModificarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ModificarClienteResult;
        
        public ModificarClienteResponseBody() {
        }
        
        public ModificarClienteResponseBody(string ModificarClienteResult) {
            this.ModificarClienteResult = ModificarClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarViabilidadCreditoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarViabilidadCredito", Namespace="http://tempuri.org/", Order=0)]
        public FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoRequestBody Body;
        
        public ValidarViabilidadCreditoRequest() {
        }
        
        public ValidarViabilidadCreditoRequest(FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarViabilidadCreditoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula;
        
        public ValidarViabilidadCreditoRequestBody() {
        }
        
        public ValidarViabilidadCreditoRequestBody(string cedula) {
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarViabilidadCreditoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarViabilidadCreditoResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoResponseBody Body;
        
        public ValidarViabilidadCreditoResponse() {
        }
        
        public ValidarViabilidadCreditoResponse(FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarViabilidadCreditoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidarViabilidadCreditoResult;
        
        public ValidarViabilidadCreditoResponseBody() {
        }
        
        public ValidarViabilidadCreditoResponseBody(string ValidarViabilidadCreditoResult) {
            this.ValidarViabilidadCreditoResult = ValidarViabilidadCreditoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarCreditoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarCredito", Namespace="http://tempuri.org/", Order=0)]
        public FrontEndWindowsForms.BackendWebService.InsertarCreditoRequestBody Body;
        
        public InsertarCreditoRequest() {
        }
        
        public InsertarCreditoRequest(FrontEndWindowsForms.BackendWebService.InsertarCreditoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarCreditoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string producto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int plazo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cedula;
        
        public InsertarCreditoRequestBody() {
        }
        
        public InsertarCreditoRequestBody(string producto, int plazo, int monto, string cedula) {
            this.producto = producto;
            this.plazo = plazo;
            this.monto = monto;
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarCreditoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarCreditoResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEndWindowsForms.BackendWebService.InsertarCreditoResponseBody Body;
        
        public InsertarCreditoResponse() {
        }
        
        public InsertarCreditoResponse(FrontEndWindowsForms.BackendWebService.InsertarCreditoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarCreditoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarCreditoResult;
        
        public InsertarCreditoResponseBody() {
        }
        
        public InsertarCreditoResponseBody(string InsertarCreditoResult) {
            this.InsertarCreditoResult = InsertarCreditoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarProductosPorClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarProductosPorCliente", Namespace="http://tempuri.org/", Order=0)]
        public FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteRequestBody Body;
        
        public ConsultarProductosPorClienteRequest() {
        }
        
        public ConsultarProductosPorClienteRequest(FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarProductosPorClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula;
        
        public ConsultarProductosPorClienteRequestBody() {
        }
        
        public ConsultarProductosPorClienteRequestBody(string cedula) {
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarProductosPorClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarProductosPorClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteResponseBody Body;
        
        public ConsultarProductosPorClienteResponse() {
        }
        
        public ConsultarProductosPorClienteResponse(FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarProductosPorClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEndWindowsForms.BackendWebService.CreditosModel[] ConsultarProductosPorClienteResult;
        
        public ConsultarProductosPorClienteResponseBody() {
        }
        
        public ConsultarProductosPorClienteResponseBody(FrontEndWindowsForms.BackendWebService.CreditosModel[] ConsultarProductosPorClienteResult) {
            this.ConsultarProductosPorClienteResult = ConsultarProductosPorClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : FrontEndWindowsForms.BackendWebService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<FrontEndWindowsForms.BackendWebService.WebServiceSoap>, FrontEndWindowsForms.BackendWebService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEndWindowsForms.BackendWebService.ListarClientesResponse FrontEndWindowsForms.BackendWebService.WebServiceSoap.ListarClientes(FrontEndWindowsForms.BackendWebService.ListarClientesRequest request) {
            return base.Channel.ListarClientes(request);
        }
        
        public FrontEndWindowsForms.BackendWebService.ClienteModel[] ListarClientes() {
            FrontEndWindowsForms.BackendWebService.ListarClientesRequest inValue = new FrontEndWindowsForms.BackendWebService.ListarClientesRequest();
            inValue.Body = new FrontEndWindowsForms.BackendWebService.ListarClientesRequestBody();
            FrontEndWindowsForms.BackendWebService.ListarClientesResponse retVal = ((FrontEndWindowsForms.BackendWebService.WebServiceSoap)(this)).ListarClientes(inValue);
            return retVal.Body.ListarClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.ListarClientesResponse> FrontEndWindowsForms.BackendWebService.WebServiceSoap.ListarClientesAsync(FrontEndWindowsForms.BackendWebService.ListarClientesRequest request) {
            return base.Channel.ListarClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.ListarClientesResponse> ListarClientesAsync() {
            FrontEndWindowsForms.BackendWebService.ListarClientesRequest inValue = new FrontEndWindowsForms.BackendWebService.ListarClientesRequest();
            inValue.Body = new FrontEndWindowsForms.BackendWebService.ListarClientesRequestBody();
            return ((FrontEndWindowsForms.BackendWebService.WebServiceSoap)(this)).ListarClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEndWindowsForms.BackendWebService.ConsultarClienteResponse FrontEndWindowsForms.BackendWebService.WebServiceSoap.ConsultarCliente(FrontEndWindowsForms.BackendWebService.ConsultarClienteRequest request) {
            return base.Channel.ConsultarCliente(request);
        }
        
        public string ConsultarCliente(string cedula) {
            FrontEndWindowsForms.BackendWebService.ConsultarClienteRequest inValue = new FrontEndWindowsForms.BackendWebService.ConsultarClienteRequest();
            inValue.Body = new FrontEndWindowsForms.BackendWebService.ConsultarClienteRequestBody();
            inValue.Body.cedula = cedula;
            FrontEndWindowsForms.BackendWebService.ConsultarClienteResponse retVal = ((FrontEndWindowsForms.BackendWebService.WebServiceSoap)(this)).ConsultarCliente(inValue);
            return retVal.Body.ConsultarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.ConsultarClienteResponse> FrontEndWindowsForms.BackendWebService.WebServiceSoap.ConsultarClienteAsync(FrontEndWindowsForms.BackendWebService.ConsultarClienteRequest request) {
            return base.Channel.ConsultarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.ConsultarClienteResponse> ConsultarClienteAsync(string cedula) {
            FrontEndWindowsForms.BackendWebService.ConsultarClienteRequest inValue = new FrontEndWindowsForms.BackendWebService.ConsultarClienteRequest();
            inValue.Body = new FrontEndWindowsForms.BackendWebService.ConsultarClienteRequestBody();
            inValue.Body.cedula = cedula;
            return ((FrontEndWindowsForms.BackendWebService.WebServiceSoap)(this)).ConsultarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEndWindowsForms.BackendWebService.EliminarClienteResponse FrontEndWindowsForms.BackendWebService.WebServiceSoap.EliminarCliente(FrontEndWindowsForms.BackendWebService.EliminarClienteRequest request) {
            return base.Channel.EliminarCliente(request);
        }
        
        public string EliminarCliente(string cedula) {
            FrontEndWindowsForms.BackendWebService.EliminarClienteRequest inValue = new FrontEndWindowsForms.BackendWebService.EliminarClienteRequest();
            inValue.Body = new FrontEndWindowsForms.BackendWebService.EliminarClienteRequestBody();
            inValue.Body.cedula = cedula;
            FrontEndWindowsForms.BackendWebService.EliminarClienteResponse retVal = ((FrontEndWindowsForms.BackendWebService.WebServiceSoap)(this)).EliminarCliente(inValue);
            return retVal.Body.EliminarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.EliminarClienteResponse> FrontEndWindowsForms.BackendWebService.WebServiceSoap.EliminarClienteAsync(FrontEndWindowsForms.BackendWebService.EliminarClienteRequest request) {
            return base.Channel.EliminarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.EliminarClienteResponse> EliminarClienteAsync(string cedula) {
            FrontEndWindowsForms.BackendWebService.EliminarClienteRequest inValue = new FrontEndWindowsForms.BackendWebService.EliminarClienteRequest();
            inValue.Body = new FrontEndWindowsForms.BackendWebService.EliminarClienteRequestBody();
            inValue.Body.cedula = cedula;
            return ((FrontEndWindowsForms.BackendWebService.WebServiceSoap)(this)).EliminarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEndWindowsForms.BackendWebService.InsertarClienteResponse FrontEndWindowsForms.BackendWebService.WebServiceSoap.InsertarCliente(FrontEndWindowsForms.BackendWebService.InsertarClienteRequest request) {
            return base.Channel.InsertarCliente(request);
        }
        
        public string InsertarCliente(string cedula, string nombre, string direccion, int ingresos, int egresos, int pasivos, int scoring) {
            FrontEndWindowsForms.BackendWebService.InsertarClienteRequest inValue = new FrontEndWindowsForms.BackendWebService.InsertarClienteRequest();
            inValue.Body = new FrontEndWindowsForms.BackendWebService.InsertarClienteRequestBody();
            inValue.Body.cedula = cedula;
            inValue.Body.nombre = nombre;
            inValue.Body.direccion = direccion;
            inValue.Body.ingresos = ingresos;
            inValue.Body.egresos = egresos;
            inValue.Body.pasivos = pasivos;
            inValue.Body.scoring = scoring;
            FrontEndWindowsForms.BackendWebService.InsertarClienteResponse retVal = ((FrontEndWindowsForms.BackendWebService.WebServiceSoap)(this)).InsertarCliente(inValue);
            return retVal.Body.InsertarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.InsertarClienteResponse> FrontEndWindowsForms.BackendWebService.WebServiceSoap.InsertarClienteAsync(FrontEndWindowsForms.BackendWebService.InsertarClienteRequest request) {
            return base.Channel.InsertarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.InsertarClienteResponse> InsertarClienteAsync(string cedula, string nombre, string direccion, int ingresos, int egresos, int pasivos, int scoring) {
            FrontEndWindowsForms.BackendWebService.InsertarClienteRequest inValue = new FrontEndWindowsForms.BackendWebService.InsertarClienteRequest();
            inValue.Body = new FrontEndWindowsForms.BackendWebService.InsertarClienteRequestBody();
            inValue.Body.cedula = cedula;
            inValue.Body.nombre = nombre;
            inValue.Body.direccion = direccion;
            inValue.Body.ingresos = ingresos;
            inValue.Body.egresos = egresos;
            inValue.Body.pasivos = pasivos;
            inValue.Body.scoring = scoring;
            return ((FrontEndWindowsForms.BackendWebService.WebServiceSoap)(this)).InsertarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEndWindowsForms.BackendWebService.ModificarClienteResponse FrontEndWindowsForms.BackendWebService.WebServiceSoap.ModificarCliente(FrontEndWindowsForms.BackendWebService.ModificarClienteRequest request) {
            return base.Channel.ModificarCliente(request);
        }
        
        public string ModificarCliente(int idCliente, string cedula, string nombre, string direccion, int ingresos, string egresos, int pasivos, int scoring) {
            FrontEndWindowsForms.BackendWebService.ModificarClienteRequest inValue = new FrontEndWindowsForms.BackendWebService.ModificarClienteRequest();
            inValue.Body = new FrontEndWindowsForms.BackendWebService.ModificarClienteRequestBody();
            inValue.Body.idCliente = idCliente;
            inValue.Body.cedula = cedula;
            inValue.Body.nombre = nombre;
            inValue.Body.direccion = direccion;
            inValue.Body.ingresos = ingresos;
            inValue.Body.egresos = egresos;
            inValue.Body.pasivos = pasivos;
            inValue.Body.scoring = scoring;
            FrontEndWindowsForms.BackendWebService.ModificarClienteResponse retVal = ((FrontEndWindowsForms.BackendWebService.WebServiceSoap)(this)).ModificarCliente(inValue);
            return retVal.Body.ModificarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.ModificarClienteResponse> FrontEndWindowsForms.BackendWebService.WebServiceSoap.ModificarClienteAsync(FrontEndWindowsForms.BackendWebService.ModificarClienteRequest request) {
            return base.Channel.ModificarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.ModificarClienteResponse> ModificarClienteAsync(int idCliente, string cedula, string nombre, string direccion, int ingresos, string egresos, int pasivos, int scoring) {
            FrontEndWindowsForms.BackendWebService.ModificarClienteRequest inValue = new FrontEndWindowsForms.BackendWebService.ModificarClienteRequest();
            inValue.Body = new FrontEndWindowsForms.BackendWebService.ModificarClienteRequestBody();
            inValue.Body.idCliente = idCliente;
            inValue.Body.cedula = cedula;
            inValue.Body.nombre = nombre;
            inValue.Body.direccion = direccion;
            inValue.Body.ingresos = ingresos;
            inValue.Body.egresos = egresos;
            inValue.Body.pasivos = pasivos;
            inValue.Body.scoring = scoring;
            return ((FrontEndWindowsForms.BackendWebService.WebServiceSoap)(this)).ModificarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoResponse FrontEndWindowsForms.BackendWebService.WebServiceSoap.ValidarViabilidadCredito(FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoRequest request) {
            return base.Channel.ValidarViabilidadCredito(request);
        }
        
        public string ValidarViabilidadCredito(string cedula) {
            FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoRequest inValue = new FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoRequest();
            inValue.Body = new FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoRequestBody();
            inValue.Body.cedula = cedula;
            FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoResponse retVal = ((FrontEndWindowsForms.BackendWebService.WebServiceSoap)(this)).ValidarViabilidadCredito(inValue);
            return retVal.Body.ValidarViabilidadCreditoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoResponse> FrontEndWindowsForms.BackendWebService.WebServiceSoap.ValidarViabilidadCreditoAsync(FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoRequest request) {
            return base.Channel.ValidarViabilidadCreditoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoResponse> ValidarViabilidadCreditoAsync(string cedula) {
            FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoRequest inValue = new FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoRequest();
            inValue.Body = new FrontEndWindowsForms.BackendWebService.ValidarViabilidadCreditoRequestBody();
            inValue.Body.cedula = cedula;
            return ((FrontEndWindowsForms.BackendWebService.WebServiceSoap)(this)).ValidarViabilidadCreditoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEndWindowsForms.BackendWebService.InsertarCreditoResponse FrontEndWindowsForms.BackendWebService.WebServiceSoap.InsertarCredito(FrontEndWindowsForms.BackendWebService.InsertarCreditoRequest request) {
            return base.Channel.InsertarCredito(request);
        }
        
        public string InsertarCredito(string producto, int plazo, int monto, string cedula) {
            FrontEndWindowsForms.BackendWebService.InsertarCreditoRequest inValue = new FrontEndWindowsForms.BackendWebService.InsertarCreditoRequest();
            inValue.Body = new FrontEndWindowsForms.BackendWebService.InsertarCreditoRequestBody();
            inValue.Body.producto = producto;
            inValue.Body.plazo = plazo;
            inValue.Body.monto = monto;
            inValue.Body.cedula = cedula;
            FrontEndWindowsForms.BackendWebService.InsertarCreditoResponse retVal = ((FrontEndWindowsForms.BackendWebService.WebServiceSoap)(this)).InsertarCredito(inValue);
            return retVal.Body.InsertarCreditoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.InsertarCreditoResponse> FrontEndWindowsForms.BackendWebService.WebServiceSoap.InsertarCreditoAsync(FrontEndWindowsForms.BackendWebService.InsertarCreditoRequest request) {
            return base.Channel.InsertarCreditoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.InsertarCreditoResponse> InsertarCreditoAsync(string producto, int plazo, int monto, string cedula) {
            FrontEndWindowsForms.BackendWebService.InsertarCreditoRequest inValue = new FrontEndWindowsForms.BackendWebService.InsertarCreditoRequest();
            inValue.Body = new FrontEndWindowsForms.BackendWebService.InsertarCreditoRequestBody();
            inValue.Body.producto = producto;
            inValue.Body.plazo = plazo;
            inValue.Body.monto = monto;
            inValue.Body.cedula = cedula;
            return ((FrontEndWindowsForms.BackendWebService.WebServiceSoap)(this)).InsertarCreditoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteResponse FrontEndWindowsForms.BackendWebService.WebServiceSoap.ConsultarProductosPorCliente(FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteRequest request) {
            return base.Channel.ConsultarProductosPorCliente(request);
        }
        
        public FrontEndWindowsForms.BackendWebService.CreditosModel[] ConsultarProductosPorCliente(string cedula) {
            FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteRequest inValue = new FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteRequest();
            inValue.Body = new FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteRequestBody();
            inValue.Body.cedula = cedula;
            FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteResponse retVal = ((FrontEndWindowsForms.BackendWebService.WebServiceSoap)(this)).ConsultarProductosPorCliente(inValue);
            return retVal.Body.ConsultarProductosPorClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteResponse> FrontEndWindowsForms.BackendWebService.WebServiceSoap.ConsultarProductosPorClienteAsync(FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteRequest request) {
            return base.Channel.ConsultarProductosPorClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteResponse> ConsultarProductosPorClienteAsync(string cedula) {
            FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteRequest inValue = new FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteRequest();
            inValue.Body = new FrontEndWindowsForms.BackendWebService.ConsultarProductosPorClienteRequestBody();
            inValue.Body.cedula = cedula;
            return ((FrontEndWindowsForms.BackendWebService.WebServiceSoap)(this)).ConsultarProductosPorClienteAsync(inValue);
        }
    }
}
